---
title: "2016 Presidential Debate: Content Breakdown"
author: "Scott Kelleher, Tulsi Gompo, Janalee Thompson"
date: "December 5, 2016"
output: html_document
---
```{r echo = FALSE, include = FALSE, message = FALSE, results = "hide"}

## specify inputs
  Speaker <- "Hilary_Clinton"  # enter Donald_Trump or Hilary_Clinton
  Debate = "Second_Debate"   # enter First_Debate or Second_Debate or Third_Debate
  google_these_words = c("Melania", "email scandal", "bigly", "nasty woman", "benghazi")  # enter up to five phrases to google in gtrends andresults
  # enter one phrase you would like to see broken down by state
  google_states = c("bigly")

##Loading libraries
library(rvest)
#library(tidyverse)
library(stringr)
library(tidytext)
library(gtrendsR)
library(tokenizers)
library(dplyr)
library(tm)
library(SnowballC)
library(wordcloud)
library(sentimentr)
library(lubridate)
library(ggplot2)
library(readr)
library(gtrendsR)
library(xml2)
#library(shiny)
library(devtools)
ls("package:gtrendsR")
library(RTextTools)
library(googleVis)
library(syuzhet)


library(RTextTools)
library(googleVis)
library(DT)
library(choroplethr)
library(choroplethrMaps)
library(syuzhet)

usr <- ("535rprogram@gmail.com")
  psw <- ("groupproject")
  ch <- gconnect(usr, psw)

  text_debate1 <- read_html("http://www.presidency.ucsb.edu/ws/index.php?pid=118971") # load the first debate page
  text_debate2 <- read_html("http://www.presidency.ucsb.edu/ws/index.php?pid=119038")  # load the second debate page
  text_debate3 <- read_html("http://www.presidency.ucsb.edu/ws/index.php?pid=119039")# load the third debate page 
  
  text_debate1 <- html_nodes(text_debate1, ".displaytext") %>% # isloate the text
    html_text() # get the text
  
  text_debate2 <- html_nodes(text_debate2, ".displaytext") %>% # isloate the text
    html_text() # get the text
  
  text_debate3 <- html_nodes(text_debate3, ".displaytext") %>% # isloate the text
    html_text() # get the text
  w <- c(text_debate1, text_debate2, text_debate3)
  
  db1 <- ymd_hms(160927020000, tz = "UTC")
  db2 <- ymd_hms(161009020000, tz = "UTC")
  db3 <-ymd_hms(161029020000, tz = "UTC")
  date_time <-c(db1, db2, db3)
```

```{r  echo = FALSE, warning = FALSE, message = FALSE}

  google_results <- gtrends(google_these_words, geo = "US", start_date = "2016-09-01", end_date = "2016-11-15")
   plot(google_results)
   
```
   

```{r echo = FALSE, include = FALSE, message = FALSE}
for (i in (1:3)) {     
  
  ##Getting the chunks of text and assigning the speaker, this just defines a function and we can place this actual code somewhere else later as long as we call the function 
  text <- w[i]
  getLines <- function(person){
    
    id <- unlist(stringr::str_extract_all(text, "[A-Z]+:")) # get the speaker
    Lines <- unlist(strsplit(text, "[A-Z]+:"))[-1]  # split by speaker (and get rid of a pesky empty line)
    Lines[id %in% person] # retain speech by relevant speaker
  }
  
  ##Creating an object called debate_lines that has two parts, one for clinton and one for trump
  debate_lines <- lapply(c("CLINTON:", "TRUMP:"), getLines) 
  
  
  ##Created two separate objects with "chunks" of text in each one, one for clinton and one for trump
  clinton_lines <- debate_lines[1] 
  trump_lines <- debate_lines[2] 
  
  
  
  
  
  #break into clinton lines
  text_clinton <- data_frame(text_c = clinton_lines[[1]]) 
 
  
  
  #break into trump lines 
  text_trump <- data_frame(text_t = trump_lines[[1]]) 
  
  
  
  ##Breaking trump lines into individual words
  trump_words <- text_trump %>%
    unnest_tokens(word, text_t)  
  #trump_words  
  
  
  #filter out the stopwords, add which debate it was and the day and time
  trump_words_unique <- !(trump_words$word %in% stopwords())
  trump_words <- mutate(trump_words, elim = trump_words_unique, debate = i, date = date_time[i])
  trump_words<- filter(trump_words, trump_words$elim == TRUE)
  trump_words <- select(trump_words, -elim)
  if(i == 1){
    all_debate_words_trump<- trump_words
  } else{
    all_debate_words_trump <- bind_rows(all_debate_words_trump, trump_words)
  }
  
  
  ##Breaking clinton lines into individual words
  clinton_words <- text_clinton %>%
    unnest_tokens(word, text_c)  
  #clinton_words
  
  
  
  #filter out the stopwords, add which debate it was and what day and time
  clinton_words_unique <- !(clinton_words$word %in% stopwords())
  clinton_words <- mutate(clinton_words, elim = clinton_words_unique, debate = i, date = date_time[i])
  clinton_words<- filter(clinton_words, clinton_words$elim == TRUE)
  clinton_words <- select(clinton_words, -elim)
  
  if(i == 1){
    all_debate_words_clinton<- clinton_words
  } else{
    all_debate_words_clinton <- bind_rows(all_debate_words_clinton, clinton_words)
  }
  
  
sentiment_clinton <- get_sentiment(as.vector(clinton_words$word))
sentiment_trump <- get_sentiment(as.vector(trump_words$word))

pwdw <- round(length(sentiment_clinton)*.1)
clinton_rolled <- zoo::rollmean(sentiment_clinton, k=pwdw)
bwdw <- round(length(sentiment_trump)*.1)
trump_rolled <- zoo::rollmean(sentiment_trump, k=bwdw)
###############this is a good comparison between the candidates, not really smoothed much 
clinton_list_getting <- rescale_x_2(clinton_rolled)
#clinton_list$x <- mutate(clinton_list$x, debate = i)
 trump_list_getting <- rescale_x_2(trump_rolled)
 #trump_list$x <- mutate(trump_list$x, debate = 1)
# 
# plot(clinton_list$x, 
#      clinton_list$z, 
#      type="l", 
#      col="blue", 
#      xlab="Narrative Time", 
#      ylab="Emotional Valence")
# lines(trump_list$x, trump_list$z, col="red")

######################################## the plots below are smoothed
poa_sample <- seq(1, length(clinton_list_getting$x), by=round(length(clinton_list_getting$x)/100))
bov_sample <- seq(1, length(trump_list_getting$x), by=round(length(trump_list_getting$x)/100))

nrc_data_c <- get_nrc_sentiment(as.vector(clinton_words$word))
nrc_data_t <- get_nrc_sentiment(as.vector(trump_words$word))


if(i == 1){ 
    clinton_x_getting <- as.data.frame(clinton_list_getting$x)
    clinton_x <- mutate(clinton_x_getting, debate = i)
    clinton_y_getting <- as.data.frame(clinton_list_getting$z)
    clinton_y <- mutate(clinton_y_getting, debate = i)
    
    trump_x_getting <- as.data.frame(trump_list_getting$x)
    trump_x <- mutate(trump_x_getting, debate = i)
    trump_y_getting <- as.data.frame(trump_list_getting$z)
    trump_y <- mutate(trump_y_getting, debate = i)
    
    clinton_emo <- as.data.frame(colSums(prop.table(nrc_data_c[, 1:8])))
    clinton_emo <- mutate(clinton_emo, debate = i)
    trump_emo <- as.data.frame(colSums(prop.table(nrc_data_t[, 1:8])))
    trump_emo <- mutate(trump_emo, debate = i)
    
    names11 <- as.data.frame(rownames(trump_emo))
    names22 <- as.data.frame(rownames(clinton_emo))
    trump_emo <- bind_cols(trump_emo, names11)
    clinton_emo <- bind_cols(clinton_emo, names22)
    
    
  } else{  
    clinton_x_getting <- as.data.frame(clinton_list_getting$x)
    clinton_x2 <- mutate(clinton_x_getting, debate = i)
    clinton_x <- bind_rows(clinton_x, clinton_x2)
    
    clinton_y_getting <- as.data.frame(clinton_list_getting$z)
    clinton_y2 <- mutate(clinton_y_getting, debate = i)
    clinton_y <- bind_rows(clinton_y, clinton_y2)
    
    trump_x_getting <- as.data.frame(trump_list_getting$x)
    trump_x2 <- mutate(trump_x_getting, debate = i)
    trump_x <- bind_rows(trump_x, trump_x2)
    
    trump_y_getting <- as.data.frame(trump_list_getting$z)
    trump_y2 <- mutate(trump_y_getting, debate = i)
    trump_y <- bind_rows(trump_y, trump_y2)
     
     clinton_emo2 <- as.data.frame(colSums(prop.table(nrc_data_c[, 1:8])))
     clinton_emo2 <- mutate(clinton_emo2, debate = i)
    trump_emo2 <- as.data.frame(colSums(prop.table(nrc_data_t[, 1:8])))
    trump_emo2 <- mutate(trump_emo2, debate = i)
    # names2 <- rownames(trump_emo2)
    # names3 <- rownames(clinton_emo2)
    
      names2 <- as.data.frame(rownames(trump_emo2))
      names3 <- as.data.frame(rownames(clinton_emo2))
    trump_emo2 <- bind_cols(trump_emo2, names2)
     trump_emo2 <- rename(trump_emo2, c(`rownames(trump_emo2)` = "rownames(trump_emo)"))
    clinton_emo2 <- bind_cols(clinton_emo2, names3) 
     clinton_emo2 <- rename(clinton_emo2, c(`rownames(clinton_emo2)` = "rownames(clinton_emo)"))
     
     clinton_emo <-  bind_rows(clinton_emo, clinton_emo2)  
     trump_emo <- bind_rows(trump_emo, trump_emo2)
     
    
  } 


# plot(clinton_list$x[poa_sample],
#      clinton_list$z[poa_sample],
#      type="l",
#      col="blue",
#      xlab="Narrative Time (sampled)",
#      ylab="Emotional Valence"
#      )
# lines(trump_list$x[bov_sample], trump_list$z[bov_sample], col="red")


  nrc_data_c <- get_nrc_sentiment(as.vector(clinton_words$word))
  nrc_data_t <- get_nrc_sentiment(as.vector(trump_words$word))
barplot(
  colSums(prop.table(nrc_data_c[, 1:8])),
  horiz = FALSE,
  cex.names = 0.7,
  las = 1,
  main = "Clinton", xlab="Emotions categories"
  )
barplot(
  colSums(prop.table(nrc_data_t[, 1:8])),
  horiz = FALSE,
  cex.names = 0.7,
  las = 1,
  main = "Trump", xlab="Emotions categories"
  )
  
print(i)
}

```

```{r   echo = FALSE, message = FALSE}
# not really using this one for anything but do not erase 
clinton_x <- rename(clinton_x, c(`clinton_list_getting$x` = "score"))
clinton_y <- rename(clinton_y, c(`clinton_list_getting$z` = "score"))

trump_x <- rename(trump_x, c(`trump_list_getting$x` = "score"))
trump_y <- rename(trump_y, c(`trump_list_getting$z` = "score"))

df_c <- data.frame(clinton_x, clinton_y)
names(df_c) <- c("clinton_plot_x", "debate", "clinton_plot_y")

df_t <- data.frame(trump_x, trump_y)
names(df_t) <- c("trump_plot_x", "debate", "trump_plot_y")

break1 <- nrow(filter(clinton_y, clinton_y$debate == "1"))
break2 <- nrow(filter(clinton_y, clinton_y$debate == "2"))
break3 <- nrow(filter(clinton_y, clinton_y$debate == "3"))

# all debates strug together                                                  ####### this plot needs a legend
ggplot(clinton_y, aes(y= score, x = seq(1, length(clinton_y$score))))+
  geom_line(color = "blue", size = 1, alpha = .4)+
  geom_line(data = trump_y, aes(y = score, x = seq(1, length(trump_y$score))), size = 1, alpha = .4, color = "red") +
  geom_vline(xintercept =(break1), size = 2, linetype = "dashed")+
  geom_vline(xintercept = (break1 + break2) , size = 2, linetype = "dashed")+
  geom_vline(xintercept = (break1 + break2+ break3) , size = 2, linetype = "dashed")+
  scale_x_continuous(breaks=c(break1, break1 + break2,break1+ break2+ break3), labels=c("debate 1", "debate 2", "debate 3"))+
  ylab("emotional valance") +
  xlab("") +
  ggtitle("Candidate emotional valance during debates") +
 geom_line(aes(y = score, colour="Clinton")) + # I added for legend
   geom_line(aes(y=score, colour ="Trump")) # I added for legend


```

```{r  echo = FALSE, message = FALSE}                               
                                                                              # this plot needs name of legend changed
trump_y$debate <- as.factor(trump_y$debate)  
ggplot(df_t, aes(y= trump_plot_y, x = trump_plot_x, colour = factor(debate)))+
  geom_line()+
  scale_fill_discrete(name = "Debate") +
  ylab("Emotional Valence")+
  xlab("Position in Debate")+
  ggtitle("Trump Emotional Valence") +
  theme(plot.title = element_text(hjust = .5))
  


```

```{r   echo = FALSE, message = FALSE}
                                                                                        # this plot needs name of legend changed
clinton_y$debate <- as.factor(clinton_y$debate)
ggplot(df_c, aes(y= clinton_plot_y, x = clinton_plot_x, colour = factor(debate)))+
  geom_line()+
  scale_fill_discrete(name = "Debate") +
  ylab("Emotional Valence")+
  xlab("Position in Debate")+
  ggtitle("Clinton Emotional Valence") +
  theme(plot.title = element_text(hjust = .5))
  
```
  
```{r echo=FALSE, message = FALSE, error= FALSE, warning = FALSE}
  #this chuck just makes a datatable of the words and can be hidden

 #  if(Speaker == "Donald_Trump"){top_used_words <- trump_most_words}
 #  if(Speaker =="Hilary_Clinton"){top_used_words<- clinton_most_words}
 # 
 # DT::datatable(as.data.frame(top_used_words), options = list(pageLength = 25))
 #  
 #  plot(top_used_words)
 #  
 #  
 #  if(Speaker == "Donald_Trump"){
 #    lines_go <- trump_lines
 #  } else if(Speaker =="Hilary_Clinton"){
 #    lines_go <- clinton_lines} 

```


  
```{r echo=FALSE, message = FALSE, error= FALSE, warning = FALSE, eval = FALSE}

#s_v <- get_sentences(lines_go)
sentiment_clinton <- get_sentiment(as.vector(clinton_words$word))
sentiment_trump <- get_sentiment(as.vector(trump_words$word))

pwdw <- round(length(sentiment_clinton)*.1)
clinton_rolled <- zoo::rollmean(sentiment_clinton, k=pwdw)
bwdw <- round(length(sentiment_trump)*.1)
trump_rolled <- zoo::rollmean(sentiment_trump, k=bwdw)
###############this is a good comparison between the candidates, not really smoothed much but still smoothed 
clinton_list <- rescale_x_2(clinton_rolled)
trump_list <- rescale_x_2(trump_rolled)

################################### this plot needs a title and a legend 
plot(clinton_list$x, 
     clinton_list$z, 
     type="l", 
     col="blue", 
     xlab="Narrative Time", 
     ylab="Emotional Valence")
lines(trump_list$x, trump_list$z, col="red")


######################################## the plots below are smoothed
poa_sample <- seq(1, length(clinton_list$x), by=round(length(clinton_list$x)/100))
bov_sample <- seq(1, length(trump_list$x), by=round(length(trump_list$x)/100))

###################################################  this plot need a title and a legend
plot(clinton_list$x[poa_sample],
     clinton_list$z[poa_sample],
     type="l",
     col="blue",
     xlab="Narrative Time (sampled)",
     ylab="Emotional Valence"
     )
lines(trump_list$x[bov_sample], trump_list$z[bov_sample], col="red")

# #################################################################################################################
# 


percent_vals <- get_percentage_values(s_v_sentiment, bins = 10)
plot(
  percent_vals,
  type="l",
  xlab = "Narrative Time",
  ylab= "Emotional Valence",
  col="red"
  )

##### smooothed response of plot above
ft_values <- get_transformed_values(
      s_v_sentiment,
      low_pass_size = 3,
      x_reverse_len = 100,
      padding_factor = 2,
      scale_vals = TRUE,
      scale_range = FALSE
      )
plot(
  ft_values,
  type ="l",
  main =Speaker,
  xlab = "Narrative Time",
  ylab = "Emotional Valence",
  col = "red"
  )


nrc_data <- get_nrc_sentiment(as.vector(clinton_words$word))

barplot(
  sort(colSums(prop.table(nrc_data[, 1:8]))),
  horiz = FALSE,
  cex.names = 0.7,
  las = 1,
  main = "Emotions in Sample text", xlab="Emotions category"
  )
```
