getwd()
library(readr)
setwd("/Users/Tulsigompo/Desktop/Brucellosis_data_final")
Bruce<-read.csv("/Users/Tulsigompo/Desktop/Brucellosis_data_final/Brucelosis_R_data_New.csv",header = TRUE, sep=",",skip = 0)
list.files()
colnames(Bruce)
table(Bruce$Place_of_Origin)
table(Bruce$Brucelosis_status)
table(Bruce$Breed)
